task:
  trainer:
    _target_: pangaea.engine.trainer.SegTrainer
    model: null
    train_loader: null
    optimizer: null
    lr_scheduler: null
    evaluator: null
    exp_dir: null
    device: null
    criterion: null
    n_epochs: 380
    precision: fp32
    ckpt_interval: 20
    eval_interval: 40
    log_interval: 5
    best_metric_key: mIoU
    use_wandb: ${use_wandb}
  evaluator:
    _target_: pangaea.engine.evaluator.SegEvaluator
    val_loader: null
    exp_dir: null
    device: null
    use_wandb: ${use_wandb}
    inference_mode: sliding
    sliding_inference_batch: 8
dataset:
  _target_: pangaea.datasets.dcc.DCC
  dataset_name: DCC
  root_path: ../data/dataset
  download_url: null
  auto_download: false
  img_size: 256
  multi_temporal: false
  multi_modal: false
  ignore_index: -1
  num_classes: 2
  classes:
    - Background
    - Building
  distribution:
    - 0.8
    - 0.2
  bands:
    optical:
      - B4
      - B3
      - B2
  data_mean:
    optical:
      - 85.40113878
      - 101.66020325
      - 74.62796492
  data_std:
    optical:
      - 52.56720269
      - 42.86468953
      - 45.01710218
  data_min:
    optical:
      - 0.0
      - 0.0
      - 0.0
  data_max:
    optical:
      - 255
      - 255
      - 255
  subset: ???
encoder:
  _target_: pangaea.encoders.scalemae_encoder.ScaleMAE_Encoder
  encoder_weights: ./pretrained_models/scalemae-vitlarge-800.pth
  download_url: https://github.com/bair-climate-initiative/scale-mae/releases/download/base-800/scalemae-vitlarge-800.pth
  embed_dim: 1024
  input_size: 224
  in_chans: 3
  patch_size: 16
  depth: 24
  num_heads: 16
  mlp_ratio: 4
  qkv_bias: true
  input_res: 1.0
  input_bands:
    optical:
      - B4
      - B3
      - B2
  output_layers:
    - 7
    - 11
    - 15
    - 23
  output_dim: 1024
decoder:
  _target_: pangaea.decoders.upernet.SegUPerNet
  channels: 512
  encoder: null
  num_classes: ${dataset.num_classes}
  finetune: ${finetune}
preprocessing:
  train:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
      - _target_: pangaea.engine.data_preprocessor.ImportanceRandomCropToEncoder
      - _target_: pangaea.engine.data_preprocessor.BandFilter
      - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd
      - _target_: pangaea.engine.data_preprocessor.BandPadding
  val:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
      - _target_: pangaea.engine.data_preprocessor.BandFilter
      - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd
      - _target_: pangaea.engine.data_preprocessor.BandPadding
  test:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
      - _target_: pangaea.engine.data_preprocessor.BandFilter
      - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd
      - _target_: pangaea.engine.data_preprocessor.BandPadding
criterion:
  _target_: torch.nn.CrossEntropyLoss
  ignore_index: ${dataset.ignore_index}
lr_scheduler:
  _target_: pangaea.utils.schedulers.MultiStepLR
  optimizer: null
  total_iters: null
  lr_milestones:
    - 0.6
    - 0.9
optimizer:
  _target_: torch.optim.AdamW
  params: null
  lr: 1.0e-06
  betas:
    - 0.9
    - 0.999
  weight_decay: 120.0
train: true
work_dir: work-dir/overregularized
seed: ???
use_wandb: false
num_workers: 8
batch_size: 4
test_num_workers: 4
test_batch_size: 1
finetune: false
ckpt_dir: ??? # work-dir/finetuned/.../checkpoint__best.pth
limited_label_train: 1
limited_label_val: 1
limited_label_strategy: stratified
stratification_bins: 3
data_replicate: 1
